(()=>{
  const ready=fn=>document.readyState==='loading'?document.addEventListener('DOMContentLoaded',fn):fn();
  ready(()=>{
    const cards=[...document.querySelectorAll('section.card')]; if(!cards.length)return;
    const key=`qcm:${location.pathname}`; let seconds=0,timer=null;
    const sequenceUrl='sequence_C1.3-C1.4_SI_gestion_donnees.html';
    const panel=document.createElement('section');panel.className='qcm-eleve-panel';panel.setAttribute('aria-label','Tableau de progression du QCM');
    panel.innerHTML=`<a class="qcm-link" href="${sequenceUrl}">← Retour à la séquence</a><div class="qcm-eleve-stats"><div class="qcm-stat"><strong id="qe-answered">0</strong>Répondues</div><div class="qcm-stat"><strong id="qe-correct">0</strong>Correctes</div><div class="qcm-stat"><strong id="qe-review">0</strong>À revoir</div><div class="qcm-stat"><strong id="qe-left">${cards.length}</strong>Restantes</div><div class="qcm-stat"><strong id="qe-time">00:00</strong>Temps</div></div><div class="qcm-progress" aria-label="Progression"><span id="qe-fill"></span></div><div class="qcm-filters"><button data-filter="all">Toutes</button><button data-filter="unanswered">Non répondues</button><button data-filter="review">À revoir</button><button data-filter="correct">Correctes</button></div><div class="qcm-actions"><button id="qe-next">Question suivante non répondue</button><button id="qe-timer">Démarrer le minuteur</button><button id="qe-print">Imprimer le bilan</button><button id="qe-clear">Effacer ma progression</button></div><div class="qcm-nav" aria-label="Navigation dans les questions"></div>`;
    const firstFooter=document.querySelector('.footer');(firstFooter||cards[0]).before(panel);
    const nav=panel.querySelector('.qcm-nav');cards.forEach((c,i)=>{c.dataset.qIndex=i+1;const b=document.createElement('button');b.textContent=i+1;b.title=`Question ${i+1}`;b.addEventListener('click',()=>c.scrollIntoView({behavior:'smooth',block:'start'}));nav.appendChild(b)});
    const fmt=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
    function isFilled(el){if(el.type==='radio'||el.type==='checkbox')return el.checked;return String(el.value||'').trim()!==''}
    function state(card){const fb=card.querySelector('.answer');if(fb?.classList.contains('ok'))return'correct';if(fb?.classList.contains('ko'))return'review';return[...card.querySelectorAll('input,select,textarea')].some(isFilled)?'answered':'unanswered'}
    function enrich(card){const fb=card.querySelector('.answer');if(!fb||(!fb.classList.contains('ok')&&!fb.classList.contains('ko'))||fb.querySelector('.qcm-enrichment'))return;const help=card.querySelector('.help')?.textContent.trim();const click=card.querySelector('button[onclick*="checkMCQ"],button[onclick*="checkSelect"],button[onclick*="checkNumber"],button[onclick*="checkTextIncludes"],button[onclick*="checkMulti"]')?.getAttribute('onclick')||'';let correct='';const m=click.match(/checkMCQ\([^,]+,\s*['"]([^'"]+)/);if(m){const input=card.querySelector(`input[value="${CSS.escape(m[1])}"]`);correct=input?.parentElement?.textContent.trim()||''}const box=document.createElement('div');box.className='qcm-enrichment';box.innerHTML=`${correct?`<p><strong>Bonne réponse :</strong> ${correct}</p>`:''}${help?`<p><strong>Pourquoi :</strong> ${help}</p>`:''}<p class="qcm-retain"><strong>À retenir :</strong> relis la notion, puis utilise « Réessayer » lorsque le bouton est proposé.</p>`;fb.appendChild(box)}
    function snapshot(){const data={seconds,fields:{}};document.querySelectorAll('input,select,textarea').forEach((el,i)=>{if(el.closest('.qcm-eleve-panel'))return;const id=el.id||`${el.name||'field'}:${i}`;data.fields[id]=el.type==='checkbox'||el.type==='radio'?el.checked:el.value});localStorage.setItem(key,JSON.stringify(data))}
    function restore(){try{const data=JSON.parse(localStorage.getItem(key)||'{}');seconds=data.seconds||0;document.querySelectorAll('input,select,textarea').forEach((el,i)=>{if(el.closest('.qcm-eleve-panel'))return;const id=el.id||`${el.name||'field'}:${i}`;if(!(id in(data.fields||{})))return;if(el.type==='checkbox'||el.type==='radio')el.checked=!!data.fields[id];else el.value=data.fields[id]})}catch(e){console.warn('Reprise QCM impossible',e)}}
    function update(){let answered=0,correct=0,review=0;cards.forEach((c,i)=>{const s=state(c);if(s!=='unanswered')answered++;if(s==='correct')correct++;if(s==='review')review++;nav.children[i].dataset.state=s;enrich(c)});panel.querySelector('#qe-answered').textContent=answered;panel.querySelector('#qe-correct').textContent=correct;panel.querySelector('#qe-review').textContent=review;panel.querySelector('#qe-left').textContent=cards.length-answered;panel.querySelector('#qe-fill').style.width=`${Math.round(answered/cards.length*100)}%`;panel.querySelector('#qe-time').textContent=fmt(seconds);snapshot()}
    restore();update();document.addEventListener('change',update);document.addEventListener('input',e=>{if(e.target.matches('input[type=text],input[type=number],textarea'))update()});new MutationObserver(update).observe(document.body,{subtree:true,attributes:true,attributeFilter:['class'],childList:true});
    panel.addEventListener('click',e=>{const f=e.target.dataset.filter;if(f){cards.forEach(c=>c.classList.toggle('qcm-hidden',f!=='all'&&state(c)!==f))}});
    panel.querySelector('#qe-next').onclick=()=>{const c=cards.find(c=>state(c)==='unanswered');c?c.scrollIntoView({behavior:'smooth',block:'start'}):alert('Toutes les questions ont reçu une réponse.')};
    panel.querySelector('#qe-timer').onclick=e=>{if(timer){clearInterval(timer);timer=null;e.target.textContent='Reprendre le minuteur'}else{timer=setInterval(()=>{seconds++;update()},1000);e.target.textContent='Mettre en pause'}};
    panel.querySelector('#qe-print').onclick=()=>window.print();
    panel.querySelector('#qe-clear').onclick=()=>{if(confirm('Effacer les réponses et la progression enregistrées sur cet appareil ?')){localStorage.removeItem(key);location.reload()}};
  });
})();
