# -*- coding: utf-8 -*-
"""Les 30 exercices de l'entraînement DNB « algorigrammes », réécrits au gabarit maison.

Chaque exercice : une question, quatre options, la bonne en premier (fix_r n'est pas
utilisé ici : l'ordre est brassé à la génération avec une graine fixe), la réfutation
de CHAQUE distracteur, une aide de niveau 1 et une de niveau 2.
"""

E = []


def ex(manche, titre, question, bonne, distracteurs, aide1, aide2, retenir,
       tag=None, img=None, pre=None):
    E.append(dict(m=manche, t=titre, q=question, bonne=bonne, dis=distracteurs,
                  a1=aide1, a2=aide2, ret=retenir, tag=tag, img=img, pre=pre))


# ══════════ Manche 1 — Le vocabulaire et les symboles ══════════
ex(1, "Ce qu'est un algorithme",
   "Parmi ces définitions, laquelle décrit un algorithme ?",
   "une suite ordonnée d'instructions qui résout un problème, exécutable pas à pas",
   [("un programme écrit en Python", "Python est UN langage possible ; un algorithme existe avant tout langage, et peut se dire en français."),
    ("un dessin technique coté", "Le dessin coté décrit une pièce dans l'espace. L'algorithme décrit un enchaînement dans le temps."),
    ("le nom d'un composant électronique", "Aucun composant ne s'appelle ainsi : c'est une méthode, pas un objet.")],
   "Pense à une recette de cuisine : des étapes, dans un ordre, qui mènent à un résultat.",
   "Deux mots comptent : « ordonnée » (l'ordre change le résultat) et « instructions » (des actions précises, sans ambiguïté).",
   "Un algorithme = des instructions, dans un ordre, pour résoudre un problème."),

ex(1, "Le losange",
   "Dans un algorigramme, à quoi sert le losange ?",
   "à poser une question fermée : une flèche entre, deux sorties étiquetées oui et non",
   [("à écrire un calcul", "Un calcul est un traitement : il va dans un rectangle, avec une seule sortie."),
    ("à marquer le début de l'algorithme", "Le début se marque avec un terminal arrondi, qui n'apparaît qu'une fois."),
    ("à afficher un résultat à l'écran", "L'affichage est une sortie de donnée : c'est le parallélogramme.")],
   "Compte les flèches qui sortent du symbole : c'est le seul qui en a deux.",
   "Le losange fait bifurquer le parcours. Ses deux sorties portent obligatoirement une étiquette, sinon le lecteur ne sait pas où aller.",
   "Losange = une question, deux sorties étiquetées.",
   img=("Images/symboles_algorigramme.svg", "Planche des cinq symboles normalisés de l'algorigramme : terminal, traitement, décision à deux sorties, entrée-sortie, flèche.")),

ex(1, "Début et fin",
   "Quel symbole marque le début et la fin d'un algorigramme ?",
   "le terminal, un rectangle aux extrémités arrondies",
   [("le losange", "Le losange pose une question ; il ne peut ni ouvrir ni fermer l'algorithme."),
    ("le parallélogramme", "Le parallélogramme sert aux entrées et aux sorties de données."),
    ("le rectangle", "Le rectangle porte un traitement, au milieu du parcours.")],
   "C'est le seul symbole aux bords arrondis.",
   "Il apparaît exactement deux fois : une pour DÉBUT, une pour FIN. Jamais au milieu du parcours.",
   "Terminal arrondi = DÉBUT et FIN, une fois chacun."),

ex(1, "Le parallélogramme",
   "L'instruction « afficher la température mesurée » se place dans :",
   "un parallélogramme : la donnée franchit la frontière du système",
   [("un rectangle", "Le rectangle sert aux traitements internes : un calcul, une affectation. Ici la donnée SORT du système."),
    ("un losange", "Aucune question n'est posée : on ne choisit rien."),
    ("un terminal", "Le terminal ne sert qu'à ouvrir et fermer l'algorithme.")],
   "Demande-toi si la donnée reste à l'intérieur du système ou si elle en sort.",
   "Entrée (lire un capteur) et sortie (afficher, envoyer) utilisent le même symbole : la donnée traverse la frontière.",
   "Parallélogramme = entrée ou sortie de donnée."),

ex(1, "Ce qu'est une variable",
   "En algorithmique, une variable est :",
   "une case mémoire qui porte un nom et dont le contenu peut changer",
   [("une valeur fixée une fois pour toutes", "Cela, c'est une constante. La variable, elle, varie — c'est son nom qui le dit."),
    ("un composant de la carte électronique", "C'est une notion logicielle : rien de physique n'est ajouté à la carte."),
    ("une erreur de programmation", "Aucun rapport : une variable est un outil normal de tout programme.")],
   "Imagine une boîte étiquetée : l'étiquette est le nom, le contenu peut être remplacé.",
   "Écrire « compteur ← 0 » crée la boîte et y met 0. Écrire « compteur ← compteur + 1 » remplace le contenu par l'ancien plus un.",
   "Variable = un nom, un contenu qui peut changer."),

ex(1, "Le mot-clé de départ",
   "Dans un algorithme écrit en langage naturel, qu'écrit-on tout en haut ?",
   "DÉBUT",
   [("SI", "SI ouvre une condition, à l'intérieur de l'algorithme, pas l'algorithme lui-même."),
    ("TANT QUE", "TANT QUE ouvre une boucle, elle aussi à l'intérieur."),
    ("AFFICHER", "AFFICHER est une instruction de sortie, qui peut se trouver n'importe où.")],
   "Le mot-clé de départ correspond au terminal arrondi de l'algorigramme.",
   "La paire DÉBUT / FIN encadre tout le reste : les déclarations de variables viennent juste après DÉBUT.",
   "DÉBUT ouvre, FIN ferme."),

ex(1, "Le mot-clé de répétition",
   "Quel mot-clé annonce qu'un bloc va se répéter ?",
   "TANT QUE",
   [("SI … ALORS", "SI choisit entre deux chemins, une seule fois : il ne répète rien."),
    ("SINON", "SINON est la deuxième branche d'un SI, pas une répétition."),
    ("AFFICHER", "AFFICHER produit une sortie ; il ne dit rien de la répétition.")],
   "Cherche le mot qui suppose qu'on revienne en arrière.",
   "Dans l'algorigramme, la répétition se voit à la flèche de retour qui remonte vers un symbole déjà traversé.",
   "TANT QUE = répétition ; SI = choix."),

ex(1, "L'ordre de lecture",
   "Dans un algorigramme sans boucle ni condition, les instructions s'exécutent :",
   "de haut en bas, en suivant les flèches",
   [("dans un ordre choisi par la machine", "La machine n'invente rien : c'est le tracé des flèches qui impose l'ordre."),
    ("de la fin vers le début", "Ce serait illisible — et le résultat n'aurait aucun sens."),
    ("une instruction sur deux", "Toutes les instructions du chemin parcouru sont exécutées.")],
   "On lit un algorigramme comme un texte : dans le sens des flèches.",
   "L'ordre EST le sens de l'algorithme : inverser deux instructions change le résultat. C'est pour cela qu'une flèche ne doit jamais laisser deux chemins possibles au même endroit.",
   "On suit les flèches, de haut en bas."),

# ══════════ Manche 2 — Lire et dérouler ══════════
ex(2, "Lire un algorithme simple",
   "Que fait cet algorithme ?",
   "il lit deux nombres et affiche leur somme",
   [("il affiche toujours 0", "Non : S reçoit A + B, dont la valeur dépend de ce qui a été lu."),
    ("il lit deux nombres et affiche le plus grand", "Aucune comparaison n'apparaît : il n'y a ni SI ni losange."),
    ("il ne fait rien tant qu'on n'appuie pas sur un bouton", "Aucune attente n'est écrite : l'algorithme se déroule dès le DÉBUT.")],
   "Lis la ligne « S ← A + B » : quel signe y figure ?",
   "Trois temps : deux entrées (Lire A, Lire B), un traitement (l'addition), une sortie (Afficher S). C'est le schéma de base entrée → traitement → sortie.",
   "Un algorithme se lit ligne à ligne, en suivant ce que devient chaque variable.",
   pre="DÉBUT\n  Lire A\n  Lire B\n  S ← A + B\n  Afficher S\nFIN"),

ex(2, "Interpréter une condition",
   "Avec x = 10, qu'affiche cette instruction ?",
   "« Petit », car 10 n'est pas strictement supérieur à 10",
   [("« Grand », car x vaut 10", "Le test demande x > 10, pas x ≥ 10 : à égalité, il est faux."),
    ("rien du tout", "Un SI … SINON affiche toujours quelque chose : l'une des deux branches est prise."),
    ("les deux, l'un après l'autre", "Les deux branches d'un SI s'excluent : on n'en prend jamais qu'une.")],
   "Compare très exactement le signe écrit et la valeur donnée.",
   "C'est le piège classique du DNB : la valeur qui tombe pile sur le seuil. « > » exclut l'égalité, « ≥ » l'inclut. Un seul caractère change la réponse.",
   "À la limite exacte, tout se joue sur > ou ≥.",
   pre="SI x > 10 ALORS\n  Afficher « Grand »\nSINON\n  Afficher « Petit »\nFIN SI"),

ex(2, "La valeur finale (1)",
   "Que vaut A à la fin ?",
   "12",
   [("5", "5 est la valeur de départ : elle est remplacée dès la deuxième ligne."),
    ("7", "7 est la valeur ajoutée, pas le résultat."),
    ("57", "Il s'agit d'une addition, pas d'une mise bout à bout des chiffres.")],
   "Remplace A par sa valeur du moment dans le membre de droite, puis calcule.",
   "La flèche ← se lit « reçoit ». On calcule d'abord la droite avec l'ancienne valeur (5 + 7 = 12), puis on range le résultat dans A.",
   "A ← A + 7 : on calcule à droite, on range à gauche.",
   pre="A ← 5\nA ← A + 7"),

ex(2, "La valeur finale (2)",
   "Que vaut n à la fin ?",
   "6",
   [("3", "3 est la valeur de départ, écrasée par la suite."),
    ("9", "9 serait le résultat si la dernière ligne était n ← n + 3."),
    ("0", "Rien ne remet n à zéro dans cet algorithme.")],
   "Traite les lignes une par une, en notant la valeur de n après chacune.",
   "Ligne 1 : n = 3. Ligne 2 : n = 3 × 2 = 6. Ligne 3 : n = 6 − 0 = 6. Un tableau de suivi à trois lignes évite toute erreur.",
   "Un tableau de suivi coûte trente secondes et fait gagner tous les points.",
   pre="n ← 3\nn ← n × 2\nn ← n − 0"),

ex(2, "Le nombre de répétitions",
   "Combien de fois « Afficher i » est-il exécuté ?",
   "5 fois, pour i valant 1, 2, 3, 4 puis 5",
   [("4 fois", "Ce serait le cas avec i < 5. Ici le test est i ≤ 5, donc 5 passe aussi."),
    ("6 fois", "i part de 1, pas de 0 : il n'y a pas de sixième tour."),
    ("une seule fois", "La flèche de retour ramène au test tant qu'il est vrai.")],
   "Écris la liste des valeurs prises par i, puis compte-les.",
   "Le nombre de tours dépend de trois choses : la valeur de départ, le test, et le pas d'incrémentation. Changer l'une des trois change le compte.",
   "Compter les tours, c'est lister les valeurs — jamais les deviner.",
   pre="i ← 1\nTANT QUE i ≤ 5 FAIRE\n  Afficher i\n  i ← i + 1\nFIN TANT QUE"),

ex(2, "La boucle qui ne tourne jamais",
   "Combien de fois le bloc s'exécute-t-il ?",
   "aucune : le test est faux dès le premier passage",
   [("une fois, car on entre toujours au moins une fois", "Faux pour TANT QUE : le test est évalué AVANT d'entrer."),
    ("indéfiniment", "Il faudrait que le test reste vrai ; ici il est faux d'emblée."),
    ("dix fois", "Aucun compteur ne va jusqu'à dix dans cet algorithme.")],
   "Évalue le test avec la valeur de départ, avant toute chose.",
   "TANT QUE teste d'abord. Si la condition est fausse au départ, le bloc n'est jamais exécuté — et c'est un comportement normal, pas un bogue.",
   "TANT QUE peut tourner zéro fois.",
   pre="i ← 10\nTANT QUE i < 5 FAIRE\n  Afficher i\n  i ← i + 1\nFIN TANT QUE"),

ex(2, "La boucle sans fin",
   "Que se passe-t-il ici ?",
   "la boucle ne s'arrête jamais : rien ne fait avancer i",
   [("elle s'exécute cinq fois", "Il faudrait que i augmente ; or i garde la valeur 1."),
    ("elle ne s'exécute pas", "Le test est vrai au départ : on entre bien dans la boucle."),
    ("elle affiche 1 puis s'arrête", "Après l'affichage, la flèche de retour ramène au test, toujours vrai.")],
   "Cherche l'instruction qui devrait modifier la variable du test.",
   "Toute boucle a besoin de trois éléments : une initialisation, un test, et une progression vers la sortie. Ici la progression manque : c'est l'erreur de boucle infinie.",
   "Une boucle sans progression vers sa sortie ne s'arrête jamais.",
   pre="i ← 1\nTANT QUE i ≤ 5 FAIRE\n  Afficher i\nFIN TANT QUE"),

ex(2, "Remettre dans l'ordre",
   "Pour préparer un thé, quel enchaînement est correct ?",
   "faire chauffer l'eau → mettre le sachet → verser l'eau → attendre → retirer le sachet",
   [("mettre le sachet → retirer le sachet → verser l'eau → attendre", "On retire le sachet avant d'avoir versé l'eau : l'infusion n'a pas lieu."),
    ("verser l'eau → faire chauffer l'eau → mettre le sachet", "L'eau est versée avant d'être chaude : le résultat n'est pas le même."),
    ("attendre → mettre le sachet → verser l'eau → faire chauffer", "Attendre avant d'avoir commencé quoi que ce soit ne sert à rien.")],
   "Demande-toi, pour chaque étape, ce qui doit être vrai avant de pouvoir la faire.",
   "C'est la propriété essentielle : un algorithme est une suite ORDONNÉE. Permuter deux étapes donne un autre résultat — parfois aucun résultat.",
   "L'ordre fait partie de l'algorithme, il n'est pas décoratif."),

# ══════════ Manche 3 — Compteurs, tests et cas limites ══════════
ex(3, "Où initialiser un compteur",
   "Un algorithme compte les défauts trouvés sur plusieurs organes. Où placer « defauts ← 0 » ?",
   "avant la boucle : le compteur doit exister avant qu'on commence à compter",
   [("à l'intérieur de la boucle, au début", "Il repartirait de zéro à chaque tour : le total final ne vaudrait jamais plus de 1."),
    ("à l'intérieur de la boucle, à la fin", "Pire encore : il effacerait le comptage juste après l'avoir fait."),
    ("après la boucle", "Trop tard : on aurait déjà essayé d'ajouter 1 à une case qui n'existe pas.")],
   "Demande-toi ce que vaudrait le compteur si l'instruction était répétée à chaque tour.",
   "C'est l'erreur la plus fréquente, et la plus discrète : le programme fonctionne, ne plante pas, et donne un résultat faux. Le tableau de suivi la révèle immédiatement.",
   "Un compteur s'initialise AVANT la boucle.",
   img=("Images/algorigramme_auto_test.svg", "Algorigramme d'un auto-test : le compteur est mis à zéro avant la boucle, incrémenté à l'intérieur, et la décision finale vient après la boucle.")),

ex(3, "Le compteur ne redescend pas",
   "Un compteur de défauts vaut 1. L'organe suivant fonctionne. Que vaut le compteur ensuite ?",
   "toujours 1 : un organe qui marche n'efface pas un défaut déjà trouvé",
   [("0, puisque le dernier organe est bon", "Le compteur mémorise le total, pas le dernier résultat."),
    ("2, puisqu'on continue à compter", "On ne compte que les défauts : un organe correct n'ajoute rien."),
    ("cela dépend de l'ordre des organes", "Une addition ne dépend pas de l'ordre : le total est le même.")],
   "Regarde ce que fait la branche « l'organe fonctionne » : ajoute-t-elle quelque chose ?",
   "La branche du oui ne contient aucune instruction : elle rejoint simplement la suite. Un compteur ne diminue que si une instruction le lui demande explicitement.",
   "Un compteur garde ce qu'il a compté.",
   img=("Images/trace_banc_essai.svg", "Trace d'exécution : le compteur passe de 0 à 1 au deuxième tour, reste à 1 au troisième malgré un organe correct, puis passe à 2.")),

ex(3, "Où placer la décision finale",
   "L'algorithme doit envoyer UN message indiquant le nombre total de défauts. Où placer le test « defauts = 0 ? » ?",
   "après la boucle : on ne peut conclure qu'une fois tous les organes testés",
   [("avant la boucle", "À ce moment-là le compteur vaut toujours 0 : le message serait systématiquement le même."),
    ("à l'intérieur de la boucle", "Le destinataire recevrait un message par organe, au lieu d'un seul."),
    ("dans la branche « organe en panne »", "Le message ne partirait que s'il y a un défaut, et autant de fois qu'il y en a.")],
   "Demande-toi à quel moment précis on connaît le total.",
   "La règle générale : une conclusion se place là où l'information nécessaire est complète. Tant que la boucle tourne, le total n'est pas connu.",
   "On conclut après la boucle, une seule fois."),

ex(3, "Traduire une condition",
   "« Au moins un défaut a été trouvé » s'écrit :",
   "defauts > 0",
   [("defauts = 0", "C'est l'inverse exact : aucun défaut."),
    ("defauts < 0", "Un compteur ne descend jamais sous zéro : ce test serait toujours faux."),
    ("defauts ≥ 1 ou defauts = 0", "La deuxième partie rend le test toujours vrai, quel que soit le compteur.")],
   "« Au moins un » veut dire un, deux, trois… mais pas zéro.",
   "Sur des entiers, defauts > 0 et defauts ≥ 1 sont équivalents. Sur des nombres décimaux, ils ne le seraient plus : la nature de la donnée compte.",
   "« Au moins un » = strictement supérieur à zéro."),

ex(3, "L'indentation",
   "À quoi sert le décalage des lignes sous un TANT QUE ?",
   "à montrer quelles instructions sont à l'intérieur de la boucle",
   [("à rendre le texte plus joli", "C'est un effet secondaire, pas la raison : le décalage porte une information."),
    ("à faire ralentir le programme", "L'indentation ne change rien à la vitesse d'exécution."),
    ("à indiquer les commentaires", "Les commentaires se signalent autrement, pas par un décalage.")],
   "Compare avec l'algorigramme : qu'est-ce qui, là-bas, dit la même chose ?",
   "Ce que l'indentation dit dans le texte, la flèche de retour le dit dans l'algorigramme : elle délimite le bloc répété. Déplacer une ligne d'un cran change le programme.",
   "L'indentation porte du sens : elle délimite le bloc répété."),

ex(3, "Le cas limite",
   "Une station teste ses organes, dont la liaison radio, et envoie son bilan PAR CETTE RADIO. Que se passe-t-il si la radio est en panne ?",
   "le message est calculé correctement mais ne part jamais : la panne est silencieuse",
   [("l'algorithme s'arrête sur une erreur", "Rien dans l'algorithme n'impose l'arrêt : il va au bout et croit avoir terminé."),
    ("le message part quand même", "Le canal est justement l'organe défaillant : il ne peut rien transmettre."),
    ("la station se répare toute seule", "Aucun algorithme ne répare un matériel défectueux.")],
   "Demande-toi par quel chemin physique le message doit passer.",
   "C'est la limite d'un auto-test : il ne peut pas signaler la panne de son propre moyen de signalement. Le remède ne s'écrit pas dans la boucle — c'est le destinataire qui doit s'inquiéter de l'ABSENCE de message.",
   "Un système d'alerte doit prouver qu'il est vivant, pas seulement dire qu'il va mal."),

# ══════════ Manche 4 — Sujets type DNB ══════════
ex(4, "Régulation de température",
   "Une serre chauffe si la température descend sous 18 °C et coupe au-dessus de 22 °C. Quel est l'intérêt de ces deux seuils différents ?",
   "éviter que le chauffage s'allume et s'éteigne sans arrêt autour d'une seule valeur",
   [("chauffer deux fois plus vite", "Les seuils ne changent pas la puissance du chauffage."),
    ("mesurer la température avec plus de précision", "La précision dépend du capteur, pas des seuils programmés."),
    ("économiser un capteur", "Un seul capteur suffit dans les deux cas.")],
   "Imagine ce qui se passerait avec un seul seuil à 20 °C et une température qui oscille autour.",
   "Avec un seul seuil, la moindre variation fait basculer le système : c'est le « clignotement », qui use le matériel. Deux seuils créent une zone neutre où rien ne change.",
   "Deux seuils = une zone neutre = pas de clignotement.",
   tag="Type DNB"),

ex(4, "Éclairage automatique",
   "Un lampadaire s'allume s'il fait nuit ET qu'une présence est détectée. Que se passe-t-il en plein jour avec une présence ?",
   "il reste éteint : les deux conditions doivent être vraies en même temps",
   [("il s'allume, car la présence suffit", "Avec un ET, une seule condition vraie ne suffit pas."),
    ("il clignote", "Rien dans l'algorithme ne fait clignoter quoi que ce soit."),
    ("il s'allume avec un retard", "Aucune temporisation n'est décrite ici.")],
   "Relis le mot qui relie les deux conditions.",
   "ET exige les deux ; OU se contente d'une seule. Remplacer l'un par l'autre change complètement le comportement — c'est une question de DNB très fréquente.",
   "ET : les deux. OU : au moins une.",
   tag="Type DNB"),

ex(4, "Calcul de moyenne",
   "Un algorithme affiche « admis » si la moyenne est supérieure ou égale à 10. Un élève a 10 exactement. Que se passe-t-il ?",
   "il est admis : le test « supérieur ou égal » inclut la valeur 10",
   [("il n'est pas admis", "Ce serait le cas avec « strictement supérieur à 10 »."),
    ("l'algorithme ne peut pas répondre", "Le test tranche toujours : il est vrai ou faux, jamais indécis."),
    ("cela dépend du nombre de notes", "La moyenne est déjà calculée : seul le test compte à ce stade.")],
   "Repère si l'énoncé dit « supérieur » ou « supérieur ou égal ».",
   "Toujours vérifier le cas qui tombe pile sur le seuil : c'est là que se cache la différence entre un algorithme juste et un algorithme presque juste.",
   "Le cas limite se teste toujours.",
   tag="Type DNB"),

ex(4, "Tri sélectif automatisé",
   "Un convoyeur trie des déchets. Un objet n'est ni métallique, ni plastique, ni verre. Que doit prévoir un algorithme correct ?",
   "une sortie par défaut, qui écarte l'objet non identifié",
   [("rien : ce cas n'arrive jamais", "Il arrive forcément : c'est même la situation la plus fréquente en usage réel."),
    ("arrêter le convoyeur définitivement", "Une seule anomalie bloquerait toute la chaîne."),
    ("le compter comme du plastique", "Ce serait une erreur de tri délibérée, qui pollue le bac.")],
   "Demande-toi ce que fait le système quand aucun test n'est vrai.",
   "Toute suite de tests doit prévoir le cas « aucun des précédents ». Sans branche par défaut, l'objet continue son chemin sans décision : c'est un trou dans l'algorithme.",
   "Toujours prévoir la branche « aucun des cas précédents ».",
   tag="Type DNB"),

ex(4, "Fabrication en série",
   "Une machine produit des pièces et doit s'arrêter après la 500ᵉ. Quelle structure utiliser ?",
   "une boucle avec un compteur, qui s'arrête quand le compteur atteint 500",
   [("500 instructions écrites à la suite", "Techniquement possible, mais illisible — et à refaire entièrement pour 600 pièces."),
    ("un simple SI … ALORS", "Un SI se traverse une fois : il ne répète rien."),
    ("aucune structure : la machine s'arrête toute seule", "Rien ne s'arrête tout seul : l'arrêt doit être programmé.")],
   "Le mot « après la 500ᵉ » suppose qu'on sait combien on en a déjà faites.",
   "Une boucle avec compteur permet de changer 500 en 600 en modifiant UN seul nombre. C'est exactement ce qu'on attend d'un bon algorithme : le paramètre se règle, la structure ne bouge pas.",
   "Un nombre de répétitions connu = une boucle avec compteur.",
   tag="Type DNB"),

ex(4, "Porte automatique",
   "Une porte automatique doit rester ouverte tant qu'une personne est détectée dans le passage. Quelle structure convient ?",
   "une boucle : tant que la présence est détectée, la porte reste ouverte",
   [("un SI unique en début de programme", "Il ne serait évalué qu'une fois : la porte se refermerait sur la personne suivante."),
    ("un compteur de 1 à 10", "Le temps d'ouverture ne dépend pas d'un nombre de tours mais de la présence réelle."),
    ("aucune structure : un capteur suffit", "Le capteur mesure ; c'est l'algorithme qui décide de garder la porte ouverte.")],
   "La condition doit être vérifiée en permanence, pas une seule fois.",
   "C'est la différence de fond entre SI et TANT QUE : le premier teste une fois, le second teste à chaque tour. Sur un système de sécurité, le choix n'est pas anodin.",
   "Une condition à surveiller en continu demande une boucle.",
   tag="Logique"),

ex(4, "Le four qui surveille",
   "Un four coupe la chauffe quand la cuisson est terminée. Quel élément fournit l'information de fin de cuisson ?",
   "un capteur, qui renseigne le système sur l'état réel du plat",
   [("l'actionneur de chauffe", "L'actionneur agit : il chauffe. Il ne mesure rien."),
    ("la variable de l'algorithme", "La variable stocke l'information : elle ne la crée pas."),
    ("l'utilisateur, obligatoirement", "S'il fallait l'utilisateur à chaque fois, le four ne serait pas automatique.")],
   "Sépare ce qui informe de ce qui agit.",
   "Capteur = entrée (il informe). Actionneur = sortie (il agit). L'algorithme est au milieu : il reçoit, décide, commande. C'est la structure de tout système automatisé.",
   "Le capteur informe, l'actionneur agit, l'algorithme décide.",
   tag="Logique"),

ex(4, "Le stock qui alerte",
   "Un magasin déclenche une commande dès que le stock passe sous 15 unités. Il en reste 15. Que fait l'algorithme si le test est « stock < 15 » ?",
   "il ne commande pas : 15 n'est pas strictement inférieur à 15",
   [("il commande, car le stock est bas", "L'algorithme n'a pas d'avis sur ce qui est « bas » : il applique le test écrit."),
    ("il commande une demi-unité", "Un test ne produit pas de résultat partiel : il est vrai ou faux."),
    ("il affiche une erreur", "Rien d'anormal ne s'est produit : le test est simplement faux.")],
   "Compare très exactement la valeur et le signe du test.",
   "Encore le cas limite. Si l'intention était « à 15 on commande », il fallait écrire « stock ≤ 15 ». L'écart entre l'intention et le code se voit uniquement en testant la valeur du seuil.",
   "Le seuil se teste avec la valeur exacte du seuil.",
   tag="Logique"),
